version: "3.7"

services:
  backend_pokemon:
    image: luisman10/backend_pokemon:1.0
    ports:
      - 8001:8000 

  frontend_pokemon:
    image: luisman10/frontend_pokemon:1.0
    ports:
      - 3001:3000 